# Generated by Django 3.1.3 on 2020-11-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile_pic', models.ImageField(upload_to='images/profile/')),
                ('signiture', models.CharField(max_length=1000)),
                ('theme', models.CharField(choices=[('1', 'classic'), ('2', 'dark'), ('3', 'light')], max_length=50)),
            ],
        ),
    ]
