# Generated by Django 3.1.3 on 2020-11-28 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math2codeCommentReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Math2codeComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_to', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Math2codeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('header_image', models.ImageField(upload_to='math2code/images/')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('problem', models.TextField()),
                ('explaination_problem', models.TextField()),
                ('code', models.FileField(upload_to='math2code/code')),
                ('code_type', models.CharField(choices=[('1', 'Python'), ('2', 'JavaScript')], default='1', max_length=25)),
                ('explaination_code', models.TextField()),
                ('url', models.URLField(blank=True, default=None, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('when_publish', models.DateTimeField(default=datetime.datetime(2020, 11, 28, 12, 12, 45, 480352))),
            ],
        ),
    ]
