# Generated by Django 3.1.1 on 2020-11-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math2codeContent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('explaination_problem', models.TextField()),
                ('code', models.FileField(upload_to='python')),
                ('explaination_code', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
