# Generated by Django 3.1.3 on 2020-11-30 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math2code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math2codecontent',
            name='when_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 17, 52, 12, 704947)),
        ),
    ]
