# Generated by Django 3.1.3 on 2020-11-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('math2code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='math2codecontent',
            name='author',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
        migrations.AddField(
            model_name='math2codecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
        migrations.AddField(
            model_name='math2codecommentreplies',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math2code.math2codecomments'),
        ),
        migrations.AddField(
            model_name='math2codecommentreplies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
    ]
