# Generated by Django 3.1.1 on 2020-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math2code', '0002_auto_20201119_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='math2codecontent',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='math2codecontent',
            name='header_image',
            field=models.ImageField(default='math2code/images/default.png', upload_to='math2code/images/'),
        ),
        migrations.AlterField(
            model_name='math2codecontent',
            name='code',
            field=models.FileField(upload_to='math2code/code'),
        ),
    ]
