# Generated by Django 3.1.1 on 2020-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math2code', '0003_auto_20201120_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math2codecontent',
            name='header_image',
            field=models.ImageField(upload_to='math2code/images/'),
        ),
    ]
