# Generated by Django 3.1.3 on 2020-11-30 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math2code', '0003_auto_20201129_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math2codecontent',
            name='when_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 18, 9, 55, 458215)),
        ),
    ]
