# Generated by Django 3.1.1 on 2020-11-22 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('math2code', '0004_auto_20201120_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='math2codecontent',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
        migrations.AddField(
            model_name='math2codecontent',
            name='code_type',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'JavaScript')], default='1', max_length=25),
        ),
        migrations.AddField(
            model_name='math2codecontent',
            name='url',
            field=models.URLField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='math2codecontent',
            name='when_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 15, 9, 46, 314520)),
        ),
        migrations.CreateModel(
            name='Math2codeComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_to', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Math2codeCommentReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math2code.math2codecomments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
        ),
    ]
