# Generated by Django 3.1.3 on 2020-11-30 02:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('math2code', '0004_auto_20201129_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math2codecommentreplies',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='math2codecomments',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='math2codecontent',
            name='when_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 18, 27, 31, 826605)),
        ),
    ]
