# Generated by Django 3.1.3 on 2020-11-30 03:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('math2code', '0005_auto_20201129_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='math2codecommentreplies',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='math2code.math2codecontent'),
        ),
        migrations.AlterField(
            model_name='math2codecommentreplies',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='profile.profile'),
        ),
        migrations.AlterField(
            model_name='math2codecomments',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profile.profile'),
        ),
        migrations.AlterField(
            model_name='math2codecontent',
            name='when_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 19, 11, 6, 337036)),
        ),
    ]
